---
- name: Converge
  hosts: all
  gather_facts: false

  tasks:
    - name: ensure tmp exists
      ansible.builtin.raw: |
        mkdir -p /tmp
        chmod 1777 /tmp
      changed_when: false

    - name: install python3 on deb
      ansible.builtin.raw: |
        if command -v apt-get >/dev/null 2>&1; then
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-apt ca-certificates
        fi
      changed_when: false

    - name: install python3 on rpm
      ansible.builtin.raw: |
        if command -v dnf >/dev/null 2>&1; then
          dnf -y install python3 ca-certificates
        elif command -v yum >/dev/null 2>&1; then
          yum -y install python3 ca-certificates
        fi
      changed_when: false

    - name: gather facts after python install
      ansible.builtin.setup:

    - name: include vector role
      ansible.builtin.include_role:
        name: vector_role

