---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove containers
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
        force_kill: true
      loop:
        - oraclelinux8
        - ubuntu

    - name: Remove network
      community.docker.docker_network:
        name: molecule
        state: absent
