---
driver:
  name: podman

platforms:
  - name: ubuntu
    image: ubuntu:latest
    command: /bin/sh -c "while true; do sleep 3600; done"
    privileged: true

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  inventory:
    group_vars:
      all:
        ansible_user: root
        ansible_become: false
        ansible_python_interpreter: /usr/bin/python3
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy
